import json
from pathlib import Path

from release_keeper.tools import run_listing_brief, run_listing_check, listing_brief, listing_check
from release_keeper.tools.listing import STORE_CAPS

EX = Path(__file__).resolve().parent.parent / "examples"
FACTS = json.loads((EX / "app_facts_example.json").read_text(encoding="utf-8"))
KO = json.loads((EX / "listing_ko_draft.json").read_text(encoding="utf-8"))


def test_caps_match_sourced_numbers():
    assert STORE_CAPS["play"] == {"title": 30, "short_description": 80, "full_description": 4000}
    assert STORE_CAPS["appstore"] == {"title": 30, "subtitle": 30, "promotional_text": 170, "full_description": 4000, "keywords": 100}


def test_ko_brief_carries_ko_template_and_facts():
    b = run_listing_brief(FACTS, language="ko", store="play")
    assert "AI 언어 모델(Google Gemini)" in b.disclosure_block
    assert "만 13세" in b.disclosure_block and "계정 삭제" in b.disclosure_block
    assert FACTS["refund_line"] in b.disclosure_block
    assert "verbatim" in b.disclosure_instruction
    assert b.output_format["json_fields"] == ["title", "short_description", "full_description"]


def test_ja_brief_instructs_translation():
    b = run_listing_brief(FACTS, language="ja", store="appstore")
    assert "Google Gemini" in b.disclosure_block and "generated by an AI language model" in b.disclosure_block
    assert "Translate this English block into ja" in b.disclosure_instruction
    assert "keywords" in b.output_format["json_fields"]


def test_ko_example_listing_passes():
    r = run_listing_check(KO, FACTS, language="ko", store="play")
    assert r.verdict != "BLOCK", r.to_json()
    assert not [f for f in r.findings if f["severity"] in ("red", "yellow")], r.to_json()
    assert r.lengths["short_description"] <= 80 and r.lengths["title"] <= 30


def test_over_cap_and_missing_disclosure_block():
    bad = {"title": "S" * 31, "short_description": "Accurate predictions of your future!" + "x" * 50,
           "full_description": "Great app. Buy Pro for $4.99/month."}
    r = run_listing_check(bad, FACTS, language="en", store="play")
    items = {f["item"]: f["severity"] for f in r.findings}
    assert r.verdict == "BLOCK"
    assert items["title_over_cap"] == "red" and items["short_description_over_cap"] == "red"
    assert items["ai_disclosure"] == "red" and items["not_advice_statement"] == "red"
    assert items["short_description_exclamation"] == "yellow"


def test_appstore_keywords_bytes_and_hygiene():
    lst = {"title": "Saju Today", "subtitle": "Daily reflection", "promotional_text": "New: share cards.",
           "keywords": "saju, fortune, today, " + "한" * 30,
           "full_description": "Every result is generated by an AI language model (Google Gemini). For reflection and entertainment — "
                               "not medical, psychological, legal, or financial advice. Refunds within 7 days; renews automatically; "
                               "cancel anytime. You must be 13 or older. Delete your account in Settings."}
    r = run_listing_check(lst, FACTS, language="en", store="appstore")
    items = {f["item"]: f["severity"] for f in r.findings}
    assert r.lengths["keywords"] > 100 and items["keywords_over_cap"] == "red"
    assert items["keywords_spaces"] == "yellow" and items["keywords_repeat_name"] == "yellow"


def test_unsupported_language_structural_only():
    ja = {"title": "サジュ・トゥデイ", "short_description": "四柱から読む一日のふりかえり",
          "full_description": "毎日の読みは AI 言語モデル（Google Gemini）が生成します。占いや医療・法律・金融の助言ではありません。"}
    r = run_listing_check(ja, FACTS, language="ja", store="play")
    assert any(p.startswith("ai_model_named") for p in r.passed)
    assert any(n.startswith("native_review") for n in r.needs_input)
    assert not any(f["item"] in ("ai_disclosure", "entertainment_framing") for f in r.findings)
    dropped = dict(ja, full_description="毎日の読みをお届けします。")
    r2 = run_listing_check(dropped, FACTS, language="ja", store="play")
    assert {f["item"]: f["severity"] for f in r2.findings}["ai_model_named"] == "red"


def test_tool_wrappers_json():
    b = json.loads(listing_brief(json.dumps(FACTS), language="ko", store="play"))
    c = json.loads(listing_check(json.dumps(KO), json.dumps(FACTS), language="ko", store="play"))
    assert b["caps"]["short_description"] == 80 and c["verdict"] in ("OK", "SHIP_WITH_FIXES")
