import json
from release_keeper.tools import run_disclosure_check, disclosure_check

SAJU_DISCLOSURE = (
    "Every reading is generated by an AI language model (Google Gemini) applying traditional "
    "Saju concepts. It is for reflection and entertainment — not a prediction of the future, "
    "and not medical, psychological, legal, or financial advice. Refunds within 7 days; cancel "
    "anytime. You can delete your account in Settings. You must be 13 or older."
)


def test_saju_template_passes():
    r = run_disclosure_check(SAJU_DISCLOSURE, has_payments=True, has_accounts=True, category="fortune")
    assert not [f for f in r.findings if f.severity == "red"], r.to_json()
    assert any(p.startswith("ai_disclosure") for p in r.passed)
    assert "not_advice_statement" in r.passed


def test_overstated_listing_blocks():
    text = "Get accurate predictions of your future from our expert reading. Fun and insightful."
    r = run_disclosure_check(text, has_payments=True, category="fortune")
    items = {f.item: f.severity for f in r.findings}
    assert items["ai_disclosure"] == "red"
    assert items["overstated_claim"] == "red"
    assert items["entertainment_framing"] == "red"
    assert items["refund_clarity"] == "yellow"
    assert json.loads(r.to_json())["summary"]["verdict"] == "BLOCK"


def test_disclosure_without_refund_is_yellow_only():
    text = ("Results are generated by an AI language model (Claude). For reflection and entertainment; "
            "not medical, legal, financial, or psychological advice. Subscription $4.99/month.")
    r = run_disclosure_check(text, has_payments=True, category="interpretation")
    sev = [f.severity for f in r.findings]
    assert "red" not in sev
    assert {f.item for f in r.findings} >= {"refund_clarity", "auto_renew_disclosure", "minimum_age"}


def test_emotional_input_requires_crisis_line():
    text = "Write how you feel today. Generated by AI (Gemini). For reflection, not psychological advice."
    r = run_disclosure_check(text, has_free_text_emotional_input=True, category="wellness")
    assert {f.item: f.severity for f in r.findings}["crisis_referral"] == "red"


def test_tool_wrapper_returns_json():
    out = json.loads(disclosure_check(SAJU_DISCLOSURE, has_payments=True, has_accounts=True, category="fortune"))
    assert out["summary"]["verdict"] in ("OK", "SHIP_WITH_FIXES")


def test_korean_negated_disclaimer_is_not_overstated():
    ko = ("모든 풀이는 AI 언어 모델(Google Gemini)이 사주 개념을 적용해 생성합니다. 성찰과 재미를 위한 것으로, "
          "미래에 대한 예언이나 의학·심리·법률·금융 조언이 아닙니다. 정확도를 보장하지 않습니다.")
    r = run_disclosure_check(ko, category="fortune")
    assert not [f for f in r.findings if f.item == "overstated_claim"], r.to_json()
    bad = run_disclosure_check("당신의 미래를 정확히 예언합니다. 결과를 보장합니다.", category="fortune")
    assert any(f.item == "overstated_claim" for f in bad.findings)


def test_framing_softener_yellow_en_ko():
    ko = "오늘의 운세로 중요한 결정에 대해 조언을 받아보세요. 모든 결과는 AI 언어 모델(Google Gemini)이 생성합니다."
    r = run_disclosure_check(ko, category="fortune")
    assert {f.item: f.severity for f in r.findings}.get("framing_softener") == "yellow", r.to_json()
    en = "Get personalized advice on love and money. Generated by an AI language model (Gemini)."
    r = run_disclosure_check(en, category="fortune")
    assert {f.item: f.severity for f in r.findings}.get("framing_softener") == "yellow"


def test_softener_ignores_negated_disclaimer():
    from pathlib import Path
    ex = Path(__file__).resolve().parent.parent / "examples"
    good = (ex / "saju_listing_good.txt").read_text(encoding="utf-8")
    r = run_disclosure_check(good, has_payments=True, has_accounts=True, category="fortune")
    assert "framing_softener" not in {f.item for f in r.findings}
    draft = json.loads((ex / "listing_ko_draft.json").read_text(encoding="utf-8"))["full_description"]
    r = run_disclosure_check(draft, has_payments=True, has_accounts=True, category="fortune")
    assert "framing_softener" not in {f.item for f in r.findings}, r.to_json()


def test_softener_exempts_crisis_and_professional_referral():
    t = ("위기 상황이라면 전문 상담을 받으세요 (findahelpline.com). If you are in crisis, please seek professional counseling. "
         "모든 결과는 AI 언어 모델(Google Gemini)이 생성합니다. 성찰과 재미를 위한 것으로, 의학·심리·법률·금융 조언이 아닙니다.")
    r = run_disclosure_check(t, has_free_text_emotional_input=True, category="wellness")
    assert "crisis_referral" in r.passed
    assert "framing_softener" not in {f.item for f in r.findings}, r.to_json()
    # the same verb outside a referral sentence still fires
    r = run_disclosure_check(t + " 오늘의 연애운에 대해 조언을 받아보세요.", has_free_text_emotional_input=True, category="wellness")
    assert "framing_softener" in {f.item for f in r.findings}


def test_renewal_phrasing_variants_pass():
    t = ("Generated by an AI language model (Gemini). For reflection and entertainment, not medical, legal, or financial advice. "
         "Pro, US$6.99 per month. It renews monthly until you cancel, and you can cancel anytime in Google Play. You must be 13 or older.")
    r = run_disclosure_check(t, has_payments=True, category="fortune")
    assert "auto_renew_disclosure" not in {f.item for f in r.findings}, r.to_json()
