"""Web surface — raw mode end to end via TestClient; agent mode must degrade to 503, never crash."""
import json
from pathlib import Path

import pytest

fastapi = pytest.importorskip("fastapi")
from fastapi.testclient import TestClient

from release_keeper.web import app

EX = Path(__file__).resolve().parent.parent / "examples"
c = TestClient(app)


def test_page_and_health():
    r = c.get("/")
    assert r.status_code == 200 and "ReleaseKeeper" in r.text and "generated by an AI language model" in r.text
    assert c.get("/health").json()["ok"] is True


def test_check_raw_blocks_bad_listing():
    r = c.post("/api/check", json={"text": (EX / "saju_listing_bad.txt").read_text(encoding="utf-8"),
                                   "payments": True, "category": "fortune", "mode": "raw"})
    assert r.status_code == 200 and r.json()["summary"]["verdict"] == "BLOCK"


def test_refund_raw_and_bad_products_json():
    ev = (EX / "rc_refund_consumable.json").read_text(encoding="utf-8")
    r = c.post("/api/refund", json={"event": ev, "products": (EX / "products.json").read_text(encoding="utf-8"), "mode": "raw"})
    assert r.status_code == 200 and r.json()["event_class"]
    assert c.post("/api/refund", json={"event": ev, "products": "{not json", "mode": "raw"}).status_code == 400


def test_notes_raw_and_missing_input():
    r = c.post("/api/notes", json={"git_log": (EX / "gitlog_sample.txt").read_text(encoding="utf-8"), "version": "1.2.0", "mode": "raw"})
    assert r.status_code == 200 and r.json()["store_whats_new_chars"] <= 500
    assert c.post("/api/notes", json={"git_log": "", "mode": "raw"}).status_code == 400


def test_listing_brief_and_check_raw():
    facts = (EX / "app_facts_example.json").read_text(encoding="utf-8")
    r = c.post("/api/listing", json={"app_facts": facts, "lang": "ko", "store": "play", "mode": "raw"})
    assert r.status_code == 200 and "output_format" in r.json()
    draft = (EX / "listing_ko_draft.json").read_text(encoding="utf-8")
    r = c.post("/api/listing", json={"app_facts": facts, "lang": "ko", "store": "play", "listing": draft})
    assert r.status_code == 200 and r.json()["verdict"] == "OK"


def test_agent_mode_without_key_is_503(monkeypatch):
    for k in ("RK_API_KEY", "OPENROUTER_API_KEY", "OPENAI_API_KEY"):
        monkeypatch.delenv(k, raising=False)
    r = c.post("/api/check", json={"text": "hello", "mode": "agent"})
    assert r.status_code == 503 and "RK_API_KEY" in r.json()["detail"]
