import json
from release_keeper.tools import run_disclosure_check, disclosure_check

SAJU_DISCLOSURE = (
    "Every reading is generated by an AI language model (Google Gemini) applying traditional "
    "Saju concepts. It is for reflection and entertainment — not a prediction of the future, "
    "and not medical, psychological, legal, or financial advice. Refunds within 7 days; cancel "
    "anytime. You can delete your account in Settings. You must be 13 or older."
)


def test_saju_template_passes():
    r = run_disclosure_check(SAJU_DISCLOSURE, has_payments=True, has_accounts=True, category="fortune")
    assert not [f for f in r.findings if f.severity == "red"], r.to_json()
    assert any(p.startswith("ai_disclosure") for p in r.passed)
    assert "not_advice_statement" in r.passed


def test_overstated_listing_blocks():
    text = "Get accurate predictions of your future from our expert reading. Fun and insightful."
    r = run_disclosure_check(text, has_payments=True, category="fortune")
    items = {f.item: f.severity for f in r.findings}
    assert items["ai_disclosure"] == "red"
    assert items["overstated_claim"] == "red"
    assert items["entertainment_framing"] == "red"
    assert items["refund_clarity"] == "yellow"
    assert json.loads(r.to_json())["summary"]["verdict"] == "BLOCK"


def test_disclosure_without_refund_is_yellow_only():
    text = ("Results are generated by an AI language model (Claude). For reflection and entertainment; "
            "not medical, legal, financial, or psychological advice. Subscription $4.99/month.")
    r = run_disclosure_check(text, has_payments=True, category="interpretation")
    sev = [f.severity for f in r.findings]
    assert "red" not in sev
    assert {f.item for f in r.findings} >= {"refund_clarity", "auto_renew_disclosure", "minimum_age"}


def test_emotional_input_requires_crisis_line():
    text = "Write how you feel today. Generated by AI (Gemini). For reflection, not psychological advice."
    r = run_disclosure_check(text, has_free_text_emotional_input=True, category="wellness")
    assert {f.item: f.severity for f in r.findings}["crisis_referral"] == "red"


def test_tool_wrapper_returns_json():
    out = json.loads(disclosure_check(SAJU_DISCLOSURE, has_payments=True, has_accounts=True, category="fortune"))
    assert out["summary"]["verdict"] in ("OK", "SHIP_WITH_FIXES")
