"""Tool 3 — listing_brief + listing_check: localized store listings that fit the caps and carry the disclosures.

Listing prose is generative, so the model writes it. What code guarantees:

* ``listing_brief``  — the per-field character caps for the target store, the
  structure to fill, the mandatory disclosure block (localized template for
  en/ko; translate-verbatim instruction for other languages), pricing/refund
  lines, and the hype vocabulary to avoid. The model drafts from this.
* ``listing_check``  — validates a drafted listing: cap violations per field,
  then the same disclosure scan as tool 1 on the full description (en/ko), or
  structural checks + a native-review flag for other languages.

Caps are taken from the stores' own help pages (fetched 2026-09-05):
Google Play "Add preview assets" — app name 30 / short 80 / full 4000,
"limits apply to both full-width and half-width characters".
App Store Connect "App information" / "Platform version information" —
name 30 / subtitle 30 / promotional text 170 / description 4000 / keywords 100 bytes.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, asdict, field
from typing import Any, Optional

from strands import tool

from .disclosure_check import CERTAINTY_PATTERNS, run_disclosure_check

STORE_CAPS = {
    "play": {"title": 30, "short_description": 80, "full_description": 4000},
    "appstore": {"title": 30, "subtitle": 30, "promotional_text": 170, "full_description": 4000, "keywords": 100},
}
KEYWORDS_UNIT = "bytes"  # App Store keywords are capped in bytes, everything else in characters

# Disclosure templates. en/ko wording follows the author's shipped app (see README "Reused material").
DISCLOSURE_TEMPLATES = {
    "en": {
        "ai": "Every result is generated by an AI language model ({model_name}).",
        "framing": "It is for reflection and entertainment — not a prediction of the future, and not medical, psychological, legal, or financial advice.",
        "refund": "{refund_line}",
        "age": "You must be {min_age} or older.",
        "deletion": "You can delete your account and data in Settings.",
    },
    "ko": {
        "ai": "모든 결과는 AI 언어 모델({model_name})이 생성합니다.",
        "framing": "성찰과 재미를 위한 것으로, 미래에 대한 예언이나 의학·심리·법률·금융 조언이 아닙니다.",
        "refund": "{refund_line}",
        "age": "만 {min_age}세 이상만 이용할 수 있습니다.",
        "deletion": "설정에서 계정 삭제 및 데이터 삭제가 가능합니다.",
    },
}
FULLY_CHECKED_LANGS = set(DISCLOSURE_TEMPLATES)  # languages tool 1's vocab covers

DEFAULT_REFUND_LINE = {
    # Neutral by design: the tool must not invent a refund window the developer never promised.
    "en": "Refunds follow the store's refund policy. Subscriptions renew automatically until cancelled; cancel anytime in the store's subscription settings.",
    "ko": "환불은 스토어의 환불 정책을 따릅니다. 구독은 해지 전까지 자동 갱신되며 스토어 구독 설정에서 언제든 해지할 수 있습니다.",
}


@dataclass
class Brief:
    store: str
    language: str
    caps: dict
    caps_unit_note: str
    structure: list[str]
    disclosure_block: str
    disclosure_instruction: str
    app: dict
    avoid_patterns: list[str]
    style: list[str]
    output_format: dict

    def to_json(self) -> str:
        return json.dumps(asdict(self), ensure_ascii=False, indent=2)


@dataclass
class CheckReport:
    store: str
    language: str
    findings: list[dict] = field(default_factory=list)
    passed: list[str] = field(default_factory=list)
    needs_input: list[str] = field(default_factory=list)
    lengths: dict = field(default_factory=dict)
    verdict: str = "OK"

    def add(self, sev: str, item: str, why: str, fix: str) -> None:
        self.findings.append({"severity": sev, "item": item, "why": why, "fix": fix})

    def finish(self) -> "CheckReport":
        order = {"red": 0, "yellow": 1, "green": 2}
        self.findings.sort(key=lambda f: order[f["severity"]])
        self.verdict = "BLOCK" if any(f["severity"] == "red" for f in self.findings) else "SHIP_WITH_FIXES" if self.findings else "OK"
        return self

    def to_json(self) -> str:
        return json.dumps(asdict(self), ensure_ascii=False, indent=2)


def _facts(app_facts: Any) -> dict:
    return json.loads(app_facts) if isinstance(app_facts, str) else dict(app_facts)


def _looks_like(text: str, lang: str) -> bool:
    """Cheap script check: ko = contains Hangul."""
    if lang == "ko":
        return re.search(r"[\uac00-\ud7a3]", text) is not None
    return True


def build_disclosure_block(app: dict, language: str) -> tuple[str, str]:
    """Returns (block, instruction). For unsupported languages the block is English + a translate-verbatim instruction."""
    lang = language if language in DISCLOSURE_TEMPLATES else "en"
    t = DISCLOSURE_TEMPLATES[lang]
    model = app.get("model_name") or "<model name>"
    lines = [t["ai"].format(model_name=model), t["framing"]]
    if app.get("has_payments"):
        refund = app.get("refund_line")
        if refund and lang != "en" and not _looks_like(refund, lang):
            # facts are usually written in English; the model copies an English refund line verbatim into a ko
            # listing even when told to translate (measured 09-05, 2/2 runs) — so use the language's default
            # line deterministically and ask the developer to confirm it matches their policy.
            refund = None
        lines.append(refund or DEFAULT_REFUND_LINE[lang])
    if app.get("has_payments") or app.get("has_accounts"):
        lines.append(t["age"].format(min_age=app.get("min_age", 13)))
    if app.get("has_accounts"):
        lines.append(t["deletion"])
    block = "\n".join(lines)
    if language in DISCLOSURE_TEMPLATES:
        instr = ("Include this block verbatim at the end of the full description. Do not soften or shorten it. "
                 "Write everything else in the target language only — no English sentences from the facts.")
        if app.get("has_payments") and app.get("refund_line") and lang != "en" and not _looks_like(app["refund_line"], lang):
            instr += (f" NOTE: refund_line in the facts is not {language}; the default {language} refund line was used — "
                      "developer must confirm it matches the actual policy (needs_input).")
    else:
        instr = (f"Translate this English block into {language} faithfully, keeping the model name '{model}' unchanged, "
                 "and place it at the end of the full description. Flag it for native-speaker review.")
    return block, instr


def run_listing_brief(app_facts: Any, *, language: str = "en", store: str = "play") -> Brief:
    if store not in STORE_CAPS:
        raise ValueError(f"store must be one of {sorted(STORE_CAPS)}")
    app = _facts(app_facts)
    block, instr = build_disclosure_block(app, language)
    caps = STORE_CAPS[store]
    structure = ["title (app name, ≤{title})".format(**caps)]
    if store == "play":
        structure.append("short_description (one line, the only copy most users read, ≤80)")
    else:
        structure.append("subtitle (≤30)")
        structure.append("promotional_text (can change without a new build, ≤170)")
        structure.append("keywords (comma-separated, ≤100 bytes, no spaces after commas, no app name)")
    structure.append("full_description: hook paragraph → 3–6 feature lines (from app.features, one benefit each) → who it is for → pricing/refund line → disclosure block (≤4000)")
    return Brief(
        store=store,
        language=language,
        caps=caps,
        caps_unit_note="Caps are characters; full-width (CJK) characters count as one. App Store keywords are capped in bytes.",
        structure=structure,
        disclosure_block=block,
        disclosure_instruction=instr,
        app=app,
        avoid_patterns=CERTAINTY_PATTERNS,
        style=[
            f"Write in {language}. Plain, concrete, second person. No exclamation marks in the title or short description.",
            "Never promise accuracy, outcomes, or professional authority; say 'reflection', 'perspectives', 'explore'.",
            "Name the AI model exactly as given in app.model_name.",
            "Do not invent features, prices, or refund terms that are not in app facts.",
        ],
        output_format={"json_fields": list(caps.keys()), "note": "Return one JSON object with exactly these fields, then call listing_check on it."},
    )


def _length(field_name: str, value: str) -> int:
    return len(value.encode("utf-8")) if field_name == "keywords" else len(value)


def run_listing_check(listing: Any, app_facts: Any, *, language: str = "en", store: str = "play") -> CheckReport:
    if store not in STORE_CAPS:
        raise ValueError(f"store must be one of {sorted(STORE_CAPS)}")
    L = json.loads(listing) if isinstance(listing, str) else dict(listing)
    app = _facts(app_facts)
    caps = STORE_CAPS[store]
    r = CheckReport(store=store, language=language)

    # 1. presence + caps
    for f_name, cap in caps.items():
        val = L.get(f_name)
        if not isinstance(val, str) or not val.strip():
            r.add("red", f"{f_name}_missing", f"Field '{f_name}' is empty; the store form will not submit.", f"Provide {f_name}.")
            continue
        n = _length(f_name, val)
        r.lengths[f_name] = n
        unit = KEYWORDS_UNIT if f_name == "keywords" else "chars"
        if n > cap:
            r.add("red", f"{f_name}_over_cap", f"{f_name} is {n} {unit}, cap is {cap}; the store rejects it.",
                  f"Cut {n - cap} {unit}. Prefer removing adjectives before removing the disclosure block.")
        elif n > cap * 0.95:
            r.add("green", f"{f_name}_near_cap", f"{f_name} is {n}/{cap} {unit}; localization or a later edit will overflow.", "Leave a little slack.")
        else:
            r.passed.append(f"{f_name}_within_cap ({n}/{cap})")
    if store == "appstore" and isinstance(L.get("keywords"), str):
        kw = L["keywords"]
        if ", " in kw:
            r.add("yellow", "keywords_spaces", "Spaces after commas waste keyword bytes.", "Use 'a,b,c' with no spaces.")
        title = (L.get("title") or "").lower()
        if title and any(w and w in kw.lower().split(",") for w in title.split()):
            r.add("yellow", "keywords_repeat_name", "Keywords repeat words from the app name; Apple already indexes the name.", "Spend the bytes on other terms.")
    for f_name in ("title", "short_description", "subtitle"):
        if isinstance(L.get(f_name), str) and "!" in L[f_name]:
            r.add("yellow", f"{f_name}_exclamation", f"'!' in {f_name} reads as hype.", "Remove it.")

    # 2. disclosure scan on the full description
    full = L.get("full_description") or ""
    lines_ = [ln.strip() for ln in full.splitlines() if len(ln.strip()) > 20]
    dups = sorted({ln for ln in lines_ if lines_.count(ln) > 1})
    if dups:
        r.add("yellow", "duplicate_line", f"{len(dups)} sentence(s) appear twice in the description, e.g. \"{dups[0][:60]}\".",
              "Keep one copy — usually the one inside the disclosure block.")
    if language == "ko":
        leaked = [ln.strip() for ln in full.splitlines()
                  if len(re.findall(r"[A-Za-z]{2,}", ln)) >= 6 and not re.search(r"[\uac00-\ud7a3]", ln)
                  and "://" not in ln and " " in ln.strip()]          # a bare URL line is not prose
        if leaked:
            r.add("red", "untranslated_line",
                  f"{len(leaked)} English sentence(s) inside the ko description, e.g. \"{leaked[0][:70]}\" — facts text copied verbatim.",
                  "Translate the line into Korean (or use the default ko refund line from listing_brief).")
    model = (app.get("model_name") or "").lower()
    if language in FULLY_CHECKED_LANGS:
        rep = run_disclosure_check(
            full,
            app_uses_ai=app.get("app_uses_ai", True),
            has_payments=bool(app.get("has_payments")),
            has_accounts=bool(app.get("has_accounts")),
            has_free_text_emotional_input=bool(app.get("has_free_text_emotional_input")),
            category=app.get("category", "general"),
        )
        for f in rep.findings:
            r.add(f.severity, f.item, f.why, f.fix)
        r.passed.extend(rep.passed)
        r.needs_input.extend(rep.needs_input)
    else:
        if not full.strip():
            pass  # already red above
        elif model and model not in full.lower():
            r.add("red", "ai_model_named", f"Model name '{app.get('model_name')}' does not appear in the {language} description; the disclosure was dropped or mistranslated.",
                  "Keep the model name unchanged inside the translated disclosure block.")
        else:
            r.passed.append(f"ai_model_named ({app.get('model_name')})")
        r.needs_input.append(f"native_review: disclosure and refund wording in '{language}' need a native-speaker check; automated vocab covers only en/ko.")
    return r.finish()


@tool
def listing_brief(app_facts_json: str, language: str = "en", store: str = "play") -> str:
    """Get everything needed to write a store listing: field caps, structure, the mandatory disclosure block, words to avoid.

    Call this first, write the listing as one JSON object with the fields in output_format.json_fields,
    then call listing_check on that JSON.

    Args:
        app_facts_json: JSON with name, tagline, category, model_name, features[], has_payments, has_accounts,
            has_free_text_emotional_input, refund_line, min_age, audience.
        language: Target language code, e.g. "en", "ko", "ja".
        store: "play" or "appstore".
    """
    return run_listing_brief(app_facts_json, language=language, store=store).to_json()


@tool
def listing_check(listing_json: str, app_facts_json: str, language: str = "en", store: str = "play") -> str:
    """Validate a drafted store listing: per-field caps, hype wording, and the required disclosures.

    Returns JSON: findings[{severity, item, why, fix}], passed[], needs_input[], lengths{}, verdict BLOCK|SHIP_WITH_FIXES|OK.
    Red = the store or a reviewer will reject it. Findings are risk flags, not legal verdicts.

    Args:
        listing_json: The listing as one JSON object (title, short_description / subtitle, promotional_text, keywords, full_description).
        app_facts_json: The same app facts passed to listing_brief.
        language: Language of the listing.
        store: "play" or "appstore".
    """
    return run_listing_check(listing_json, app_facts_json, language=language, store=store).to_json()
